baseURL = "http://my-bucket-aws-polly.s3-website.eu-west-2.amazonaws.com"
languageCode = "en-us"
defaultContentLanguage="en"
title = "AWS Polly website"
theme="hugo-theme-learn-master"
defaultContentLanguageInSubdur = true
uglyurls = true

[params]
	description = "New website"
	author = "Me"
	showVisitedLinks = true
	pollyMediaURL = "https://s3.eu-west-2.amazonaws.com/my-bucket-polly-output"
	
[Languages]
[Languages.en]
title = "AWS Polly website"
weight = 1
languageName = "English"

[Languages.fr]
title = "AWS Polly website"
weight = 2
languageName = "Francais"
